name: Infra CD

on:
  workflow_dispatch:

  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform-apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: "access_token"
          workload_identity_provider: "projects/703716690424/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "github-deployer@datamanagemenplatformdev.iam.gserviceaccount.com"

      - name: Initialize Terraform
        working-directory: ./infra
        run: terraform init

      - name: Force unlock state (if locked)
        working-directory: ./infra
        run: |
          # Force unlock any existing state locks
          # Using 0 as the lock ID will unlock any existing lock regardless of its actual ID
          terraform force-unlock -force 0 || true
        continue-on-error: true

      - name: Plan Terraform
        working-directory: ./infra
        run: terraform plan -out=tfplan

      - name: Apply Terraform
        working-directory: ./infra
        run: terraform apply -auto-approve tfplan
